-- Add up migration script here
-- Make sure pgcrypto extension is enabled for gen_random_uuid()
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

insert into "integration" ("subject", "name") values ('NmMLjTtX0XrnWjbe1JbRAgwEmn5lP3Sg@clients', 'session');

INSERT INTO "game_base" (
    id,
    name,
    description,
    game_type,
    category,
    iterations,
    times_played,
    last_played
) VALUES
-- 10 Quiz games (User Provided)
(gen_random_uuid(), 'Quiz Game 1', 'A fun quiz game', 'quiz', 'casual', 5, 10, NOW()),
(gen_random_uuid(), 'Quiz Game 2', 'Test your knowledge', 'quiz', 'random', 3, 7, NOW() - INTERVAL '1 day'),
(gen_random_uuid(), 'Quiz Game 3', NULL, 'quiz', 'ladies', 8, 15, NOW() - INTERVAL '2 days'),
(gen_random_uuid(), 'Quiz Game 4', 'Challenging quiz', 'quiz', 'boys', 6, 12, NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Quiz Game 5', NULL, 'quiz', 'default', 4, 5, NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Quiz Game 6', 'Another quiz', 'quiz', 'casual', 7, 20, NOW() - INTERVAL '5 days'),
(gen_random_uuid(), 'Quiz Game 7', NULL, 'quiz', 'random', 2, 3, NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Quiz Game 8', 'Fun challenge', 'quiz', 'ladies', 9, 18, NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Quiz Game 9', 'Brain teaser', 'quiz', 'boys', 5, 10, NOW() - INTERVAL '8 days'),
(gen_random_uuid(), 'Quiz Game 10', NULL, 'quiz', 'default', 6, 9, NOW() - INTERVAL '9 days'),

-- 70 ADDITIONAL Quiz games (11 through 80)
-- last_played continues from 10 days ago up to 79 days ago, cycling through categories
(gen_random_uuid(), 'Quiz Game 11', 'Test of general knowledge', 'quiz', 'casual', 5, 11, NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Quiz Game 12', NULL, 'quiz', 'random', 4, 8, NOW() - INTERVAL '11 days'),
(gen_random_uuid(), 'Quiz Game 13', 'Quick fire questions', 'quiz', 'ladies', 6, 16, NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Quiz Game 14', NULL, 'quiz', 'boys', 7, 13, NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Quiz Game 15', 'Trivia challenge', 'quiz', 'default', 3, 6, NOW() - INTERVAL '14 days'),
(gen_random_uuid(), 'Quiz Game 16', 'Category knowledge quiz', 'quiz', 'casual', 8, 21, NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Quiz Game 17', NULL, 'quiz', 'random', 3, 4, NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Quiz Game 18', 'Difficulty: Hard', 'quiz', 'ladies', 10, 19, NOW() - INTERVAL '17 days'),
(gen_random_uuid(), 'Quiz Game 19', NULL, 'quiz', 'boys', 6, 11, NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Quiz Game 20', 'Another brain teaser', 'quiz', 'default', 7, 10, NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Quiz Game 21', 'Test of general knowledge', 'quiz', 'casual', 5, 12, NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Quiz Game 22', NULL, 'quiz', 'random', 4, 9, NOW() - INTERVAL '21 days'),
(gen_random_uuid(), 'Quiz Game 23', 'Quick fire questions', 'quiz', 'ladies', 6, 17, NOW() - INTERVAL '22 days'),
(gen_random_uuid(), 'Quiz Game 24', NULL, 'quiz', 'boys', 7, 14, NOW() - INTERVAL '23 days'),
(gen_random_uuid(), 'Quiz Game 25', 'Trivia challenge', 'quiz', 'default', 3, 7, NOW() - INTERVAL '24 days'),
(gen_random_uuid(), 'Quiz Game 26', 'Category knowledge quiz', 'quiz', 'casual', 8, 22, NOW() - INTERVAL '25 days'),
(gen_random_uuid(), 'Quiz Game 27', NULL, 'quiz', 'random', 3, 5, NOW() - INTERVAL '26 days'),
(gen_random_uuid(), 'Quiz Game 28', 'Difficulty: Hard', 'quiz', 'ladies', 10, 20, NOW() - INTERVAL '27 days'),
(gen_random_uuid(), 'Quiz Game 29', NULL, 'quiz', 'boys', 6, 12, NOW() - INTERVAL '28 days'),
(gen_random_uuid(), 'Quiz Game 30', 'Another brain teaser', 'quiz', 'default', 7, 11, NOW() - INTERVAL '29 days'),
(gen_random_uuid(), 'Quiz Game 31', 'Test of general knowledge', 'quiz', 'casual', 5, 13, NOW() - INTERVAL '30 days'),
(gen_random_uuid(), 'Quiz Game 32', NULL, 'quiz', 'random', 4, 10, NOW() - INTERVAL '31 days'),
(gen_random_uuid(), 'Quiz Game 33', 'Quick fire questions', 'quiz', 'ladies', 6, 18, NOW() - INTERVAL '32 days'),
(gen_random_uuid(), 'Quiz Game 34', NULL, 'quiz', 'boys', 7, 15, NOW() - INTERVAL '33 days'),
(gen_random_uuid(), 'Quiz Game 35', 'Trivia challenge', 'quiz', 'default', 3, 8, NOW() - INTERVAL '34 days'),
(gen_random_uuid(), 'Quiz Game 36', 'Category knowledge quiz', 'quiz', 'casual', 8, 23, NOW() - INTERVAL '35 days'),
(gen_random_uuid(), 'Quiz Game 37', NULL, 'quiz', 'random', 3, 6, NOW() - INTERVAL '36 days'),
(gen_random_uuid(), 'Quiz Game 38', 'Difficulty: Hard', 'quiz', 'ladies', 10, 21, NOW() - INTERVAL '37 days'),
(gen_random_uuid(), 'Quiz Game 39', NULL, 'quiz', 'boys', 6, 13, NOW() - INTERVAL '38 days'),
(gen_random_uuid(), 'Quiz Game 40', 'Another brain teaser', 'quiz', 'default', 7, 12, NOW() - INTERVAL '39 days'),
(gen_random_uuid(), 'Quiz Game 41', 'Test of general knowledge', 'quiz', 'casual', 5, 14, NOW() - INTERVAL '40 days'),
(gen_random_uuid(), 'Quiz Game 42', NULL, 'quiz', 'random', 4, 11, NOW() - INTERVAL '41 days'),
(gen_random_uuid(), 'Quiz Game 43', 'Quick fire questions', 'quiz', 'ladies', 6, 19, NOW() - INTERVAL '42 days'),
(gen_random_uuid(), 'Quiz Game 44', NULL, 'quiz', 'boys', 7, 16, NOW() - INTERVAL '43 days'),
(gen_random_uuid(), 'Quiz Game 45', 'Trivia challenge', 'quiz', 'default', 3, 9, NOW() - INTERVAL '44 days'),
(gen_random_uuid(), 'Quiz Game 46', 'Category knowledge quiz', 'quiz', 'casual', 8, 24, NOW() - INTERVAL '45 days'),
(gen_random_uuid(), 'Quiz Game 47', NULL, 'quiz', 'random', 3, 7, NOW() - INTERVAL '46 days'),
(gen_random_uuid(), 'Quiz Game 48', 'Difficulty: Hard', 'quiz', 'ladies', 10, 22, NOW() - INTERVAL '47 days'),
(gen_random_uuid(), 'Quiz Game 49', NULL, 'quiz', 'boys', 6, 14, NOW() - INTERVAL '48 days'),
(gen_random_uuid(), 'Quiz Game 50', 'Another brain teaser', 'quiz', 'default', 7, 13, NOW() - INTERVAL '49 days'),
(gen_random_uuid(), 'Quiz Game 51', 'Test of general knowledge', 'quiz', 'casual', 5, 15, NOW() - INTERVAL '50 days'),
(gen_random_uuid(), 'Quiz Game 52', NULL, 'quiz', 'random', 4, 12, NOW() - INTERVAL '51 days'),
(gen_random_uuid(), 'Quiz Game 53', 'Quick fire questions', 'quiz', 'ladies', 6, 20, NOW() - INTERVAL '52 days'),
(gen_random_uuid(), 'Quiz Game 54', NULL, 'quiz', 'boys', 7, 17, NOW() - INTERVAL '53 days'),
(gen_random_uuid(), 'Quiz Game 55', 'Trivia challenge', 'quiz', 'default', 3, 10, NOW() - INTERVAL '54 days'),
(gen_random_uuid(), 'Quiz Game 56', 'Category knowledge quiz', 'quiz', 'casual', 8, 25, NOW() - INTERVAL '55 days'),
(gen_random_uuid(), 'Quiz Game 57', NULL, 'quiz', 'random', 3, 8, NOW() - INTERVAL '56 days'),
(gen_random_uuid(), 'Quiz Game 58', 'Difficulty: Hard', 'quiz', 'ladies', 10, 23, NOW() - INTERVAL '57 days'),
(gen_random_uuid(), 'Quiz Game 59', NULL, 'quiz', 'boys', 6, 15, NOW() - INTERVAL '58 days'),
(gen_random_uuid(), 'Quiz Game 60', 'Another brain teaser', 'quiz', 'default', 7, 14, NOW() - INTERVAL '59 days'),
(gen_random_uuid(), 'Quiz Game 61', 'Test of general knowledge', 'quiz', 'casual', 5, 16, NOW() - INTERVAL '60 days'),
(gen_random_uuid(), 'Quiz Game 62', NULL, 'quiz', 'random', 4, 13, NOW() - INTERVAL '61 days'),
(gen_random_uuid(), 'Quiz Game 63', 'Quick fire questions', 'quiz', 'ladies', 6, 21, NOW() - INTERVAL '62 days'),
(gen_random_uuid(), 'Quiz Game 64', NULL, 'quiz', 'boys', 7, 18, NOW() - INTERVAL '63 days'),
(gen_random_uuid(), 'Quiz Game 65', 'Trivia challenge', 'quiz', 'default', 3, 11, NOW() - INTERVAL '64 days'),
(gen_random_uuid(), 'Quiz Game 66', 'Category knowledge quiz', 'quiz', 'casual', 8, 26, NOW() - INTERVAL '65 days'),
(gen_random_uuid(), 'Quiz Game 67', NULL, 'quiz', 'random', 3, 9, NOW() - INTERVAL '66 days'),
(gen_random_uuid(), 'Quiz Game 68', 'Difficulty: Hard', 'quiz', 'ladies', 10, 24, NOW() - INTERVAL '67 days'),
(gen_random_uuid(), 'Quiz Game 69', NULL, 'quiz', 'boys', 6, 16, NOW() - INTERVAL '68 days'),
(gen_random_uuid(), 'Quiz Game 70', 'Another brain teaser', 'quiz', 'default', 7, 15, NOW() - INTERVAL '69 days'),
(gen_random_uuid(), 'Quiz Game 71', 'Test of general knowledge', 'quiz', 'casual', 5, 17, NOW() - INTERVAL '70 days'),
(gen_random_uuid(), 'Quiz Game 72', NULL, 'quiz', 'random', 4, 14, NOW() - INTERVAL '71 days'),
(gen_random_uuid(), 'Quiz Game 73', 'Quick fire questions', 'quiz', 'ladies', 6, 22, NOW() - INTERVAL '72 days'),
(gen_random_uuid(), 'Quiz Game 74', NULL, 'quiz', 'boys', 7, 19, NOW() - INTERVAL '73 days'),
(gen_random_uuid(), 'Quiz Game 75', 'Trivia challenge', 'quiz', 'default', 3, 12, NOW() - INTERVAL '74 days'),
(gen_random_uuid(), 'Quiz Game 76', 'Category knowledge quiz', 'quiz', 'casual', 8, 27, NOW() - INTERVAL '75 days'),
(gen_random_uuid(), 'Quiz Game 77', NULL, 'quiz', 'random', 3, 10, NOW() - INTERVAL '76 days'),
(gen_random_uuid(), 'Quiz Game 78', 'Fun challenge', 'quiz', 'ladies', 10, 25, NOW() - INTERVAL '77 days'),
(gen_random_uuid(), 'Quiz Game 79', NULL, 'quiz', 'boys', 6, 17, NOW() - INTERVAL '78 days'),
(gen_random_uuid(), 'Quiz Game 80', 'Final quiz challenge', 'quiz', 'default', 7, 16, NOW() - INTERVAL '79 days'),

-- 10 Spin games (User Provided)
(gen_random_uuid(), 'Spin Game 1', 'Spin to win', 'spin', 'casual', 3, 8, NOW()),
(gen_random_uuid(), 'Spin Game 2', NULL, 'spin', 'random', 4, 10, NOW() - INTERVAL '1 day'),
(gen_random_uuid(), 'Spin Game 3', 'Try your luck', 'spin', 'ladies', 6, 12, NOW() - INTERVAL '2 days'),
(gen_random_uuid(), 'Spin Game 4', NULL, 'spin', 'boys', 5, 9, NOW() - INTERVAL '3 days'),
(gen_random_uuid(), 'Spin Game 5', 'Big prizes', 'spin', 'default', 7, 15, NOW() - INTERVAL '4 days'),
(gen_random_uuid(), 'Spin Game 6', NULL, 'spin', 'casual', 2, 4, NOW() - INTERVAL '5 days'),
(gen_random_uuid(), 'Spin Game 7', 'Lucky spin', 'spin', 'random', 8, 20, NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Spin Game 8', NULL, 'spin', 'ladies', 3, 7, NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Spin Game 9', 'Try again', 'spin', 'boys', 4, 11, NOW() - INTERVAL '8 days'),
(gen_random_uuid(), 'Spin Game 10', NULL, 'spin', 'default', 5, 9, NOW() - INTERVAL '9 days'),

-- 70 ADDITIONAL Spin games (11 through 80)
-- last_played continues from 80 days ago up to 149 days ago, cycling through categories
(gen_random_uuid(), 'Spin Game 11', 'Spin for tokens', 'spin', 'casual', 4, 9, NOW() - INTERVAL '80 days'),
(gen_random_uuid(), 'Spin Game 12', 'Wheel of fortune', 'spin', 'random', 5, 11, NOW() - INTERVAL '81 days'),
(gen_random_uuid(), 'Spin Game 13', NULL, 'spin', 'ladies', 7, 13, NOW() - INTERVAL '82 days'),
(gen_random_uuid(), 'Spin Game 14', 'The jackpot spinner', 'spin', 'boys', 6, 10, NOW() - INTERVAL '83 days'),
(gen_random_uuid(), 'Spin Game 15', NULL, 'spin', 'default', 8, 16, NOW() - INTERVAL '84 days'),
(gen_random_uuid(), 'Spin Game 16', 'Simple spin', 'spin', 'casual', 3, 5, NOW() - INTERVAL '85 days'),
(gen_random_uuid(), 'Spin Game 17', NULL, 'spin', 'random', 9, 21, NOW() - INTERVAL '86 days'),
(gen_random_uuid(), 'Spin Game 18', 'Lady luck spin', 'spin', 'ladies', 4, 8, NOW() - INTERVAL '87 days'),
(gen_random_uuid(), 'Spin Game 19', NULL, 'spin', 'boys', 5, 12, NOW() - INTERVAL '88 days'),
(gen_random_uuid(), 'Spin Game 20', 'Final spin round', 'spin', 'default', 6, 10, NOW() - INTERVAL '89 days'),
(gen_random_uuid(), 'Spin Game 21', 'Spin for tokens', 'spin', 'casual', 4, 10, NOW() - INTERVAL '90 days'),
(gen_random_uuid(), 'Spin Game 22', 'Wheel of fortune', 'spin', 'random', 5, 12, NOW() - INTERVAL '91 days'),
(gen_random_uuid(), 'Spin Game 23', NULL, 'spin', 'ladies', 7, 14, NOW() - INTERVAL '92 days'),
(gen_random_uuid(), 'Spin Game 24', 'The jackpot spinner', 'spin', 'boys', 6, 11, NOW() - INTERVAL '93 days'),
(gen_random_uuid(), 'Spin Game 25', NULL, 'spin', 'default', 8, 17, NOW() - INTERVAL '94 days'),
(gen_random_uuid(), 'Spin Game 26', 'Simple spin', 'spin', 'casual', 3, 6, NOW() - INTERVAL '95 days'),
(gen_random_uuid(), 'Spin Game 27', NULL, 'spin', 'random', 9, 22, NOW() - INTERVAL '96 days'),
(gen_random_uuid(), 'Spin Game 28', 'Lady luck spin', 'spin', 'ladies', 4, 9, NOW() - INTERVAL '97 days'),
(gen_random_uuid(), 'Spin Game 29', NULL, 'spin', 'boys', 5, 13, NOW() - INTERVAL '98 days'),
(gen_random_uuid(), 'Spin Game 30', 'Final spin round', 'spin', 'default', 6, 11, NOW() - INTERVAL '99 days'),
(gen_random_uuid(), 'Spin Game 31', 'Spin for tokens', 'spin', 'casual', 4, 11, NOW() - INTERVAL '100 days'),
(gen_random_uuid(), 'Spin Game 32', 'Wheel of fortune', 'spin', 'random', 5, 13, NOW() - INTERVAL '101 days'),
(gen_random_uuid(), 'Spin Game 33', NULL, 'spin', 'ladies', 7, 15, NOW() - INTERVAL '102 days'),
(gen_random_uuid(), 'Spin Game 34', 'The jackpot spinner', 'spin', 'boys', 6, 12, NOW() - INTERVAL '103 days'),
(gen_random_uuid(), 'Spin Game 35', NULL, 'spin', 'default', 8, 18, NOW() - INTERVAL '104 days'),
(gen_random_uuid(), 'Spin Game 36', 'Simple spin', 'spin', 'casual', 3, 7, NOW() - INTERVAL '105 days'),
(gen_random_uuid(), 'Spin Game 37', NULL, 'spin', 'random', 9, 23, NOW() - INTERVAL '106 days'),
(gen_random_uuid(), 'Spin Game 38', 'Lady luck spin', 'spin', 'ladies', 4, 10, NOW() - INTERVAL '107 days'),
(gen_random_uuid(), 'Spin Game 39', NULL, 'spin', 'boys', 5, 14, NOW() - INTERVAL '108 days'),
(gen_random_uuid(), 'Spin Game 40', 'Final spin round', 'spin', 'default', 6, 12, NOW() - INTERVAL '109 days'),
(gen_random_uuid(), 'Spin Game 41', 'Spin for tokens', 'spin', 'casual', 4, 12, NOW() - INTERVAL '110 days'),
(gen_random_uuid(), 'Spin Game 42', 'Wheel of fortune', 'spin', 'random', 5, 14, NOW() - INTERVAL '111 days'),
(gen_random_uuid(), 'Spin Game 43', NULL, 'spin', 'ladies', 7, 16, NOW() - INTERVAL '112 days'),
(gen_random_uuid(), 'Spin Game 44', 'The jackpot spinner', 'spin', 'boys', 6, 13, NOW() - INTERVAL '113 days'),
(gen_random_uuid(), 'Spin Game 45', NULL, 'spin', 'default', 8, 19, NOW() - INTERVAL '114 days'),
(gen_random_uuid(), 'Spin Game 46', 'Simple spin', 'spin', 'casual', 3, 8, NOW() - INTERVAL '115 days'),
(gen_random_uuid(), 'Spin Game 47', NULL, 'spin', 'random', 9, 24, NOW() - INTERVAL '116 days'),
(gen_random_uuid(), 'Spin Game 48', 'Lady luck spin', 'spin', 'ladies', 4, 11, NOW() - INTERVAL '117 days'),
(gen_random_uuid(), 'Spin Game 49', NULL, 'spin', 'boys', 5, 15, NOW() - INTERVAL '118 days'),
(gen_random_uuid(), 'Spin Game 50', 'Final spin round', 'spin', 'default', 6, 13, NOW() - INTERVAL '119 days'),
(gen_random_uuid(), 'Spin Game 51', 'Spin for tokens', 'spin', 'casual', 4, 13, NOW() - INTERVAL '120 days'),
(gen_random_uuid(), 'Spin Game 52', 'Wheel of fortune', 'spin', 'random', 5, 15, NOW() - INTERVAL '121 days'),
(gen_random_uuid(), 'Spin Game 53', NULL, 'spin', 'ladies', 7, 17, NOW() - INTERVAL '122 days'),
(gen_random_uuid(), 'Spin Game 54', 'The jackpot spinner', 'spin', 'boys', 6, 14, NOW() - INTERVAL '123 days'),
(gen_random_uuid(), 'Spin Game 55', NULL, 'spin', 'default', 8, 20, NOW() - INTERVAL '124 days'),
(gen_random_uuid(), 'Spin Game 56', 'Simple spin', 'spin', 'casual', 3, 9, NOW() - INTERVAL '125 days'),
(gen_random_uuid(), 'Spin Game 57', NULL, 'spin', 'random', 9, 25, NOW() - INTERVAL '126 days'),
(gen_random_uuid(), 'Spin Game 58', 'Lady luck spin', 'spin', 'ladies', 4, 12, NOW() - INTERVAL '127 days'),
(gen_random_uuid(), 'Spin Game 59', NULL, 'spin', 'boys', 5, 16, NOW() - INTERVAL '128 days'),
(gen_random_uuid(), 'Spin Game 60', 'Final spin round', 'spin', 'default', 6, 14, NOW() - INTERVAL '129 days'),
(gen_random_uuid(), 'Spin Game 61', 'Spin for tokens', 'spin', 'casual', 4, 14, NOW() - INTERVAL '130 days'),
(gen_random_uuid(), 'Spin Game 62', 'Wheel of fortune', 'spin', 'random', 5, 16, NOW() - INTERVAL '131 days'),
(gen_random_uuid(), 'Spin Game 63', NULL, 'spin', 'ladies', 7, 18, NOW() - INTERVAL '132 days'),
(gen_random_uuid(), 'Spin Game 64', 'The jackpot spinner', 'spin', 'boys', 6, 15, NOW() - INTERVAL '133 days'),
(gen_random_uuid(), 'Spin Game 65', NULL, 'spin', 'default', 8, 21, NOW() - INTERVAL '134 days'),
(gen_random_uuid(), 'Spin Game 66', 'Simple spin', 'spin', 'casual', 3, 10, NOW() - INTERVAL '135 days'),
(gen_random_uuid(), 'Spin Game 67', NULL, 'spin', 'random', 9, 26, NOW() - INTERVAL '136 days'),
(gen_random_uuid(), 'Spin Game 68', 'Lady luck spin', 'spin', 'ladies', 4, 13, NOW() - INTERVAL '137 days'),
(gen_random_uuid(), 'Spin Game 69', NULL, 'spin', 'boys', 5, 17, NOW() - INTERVAL '138 days'),
(gen_random_uuid(), 'Spin Game 70', 'Final spin round', 'spin', 'default', 6, 15, NOW() - INTERVAL '139 days'),
(gen_random_uuid(), 'Spin Game 71', 'Spin for tokens', 'spin', 'casual', 4, 15, NOW() - INTERVAL '140 days'),
(gen_random_uuid(), 'Spin Game 72', 'Wheel of fortune', 'spin', 'random', 5, 17, NOW() - INTERVAL '141 days'),
(gen_random_uuid(), 'Spin Game 73', NULL, 'spin', 'ladies', 7, 19, NOW() - INTERVAL '142 days'),
(gen_random_uuid(), 'Spin Game 74', 'The jackpot spinner', 'spin', 'boys', 6, 16, NOW() - INTERVAL '143 days'),
(gen_random_uuid(), 'Spin Game 75', NULL, 'spin', 'default', 8, 22, NOW() - INTERVAL '144 days'),
(gen_random_uuid(), 'Spin Game 76', 'Simple spin', 'spin', 'casual', 3, 11, NOW() - INTERVAL '145 days'),
(gen_random_uuid(), 'Spin Game 77', NULL, 'spin', 'random', 9, 27, NOW() - INTERVAL '146 days'),
(gen_random_uuid(), 'Spin Game 78', 'Lady luck spin', 'spin', 'ladies', 4, 14, NOW() - INTERVAL '147 days'),
(gen_random_uuid(), 'Spin Game 79', NULL, 'spin', 'boys', 5, 18, NOW() - INTERVAL '148 days'),
(gen_random_uuid(), 'Spin Game 80', 'Ultimate spin challenge', 'spin', 'default', 6, 16, NOW() - INTERVAL '149 days');