[server]
address = "127.0.0.1"
port = 3000
gs_domain = "http://localhost:9000"
page_size = 5

[auth0]
domain = "https://dev-tero.eu.auth0.com/"
audience = "https://api.tero.com"
client_id = "placeholder"
webhook_key = "placeholder"
mgmt_client_id = "oqaR79eS8q36bUnERUIzzRfGaHpTRHN1"

[[integrations]]
subject = "NmMLjTtX0XrnWjbe1JbRAgwEmn5lP3Sg"
name = "session"

[[integrations]]
subject = "oqaR79eS8q36bUnERUIzzRfGaHpTRHN1"
name = "platform"
