[server]
address = "0.0.0.0"
port = 8080
gs_domain = "https://terosession-production-34ce.up.railway.app"
page_size = 20

[auth0]
domain = "https://dev-tero.eu.auth0.com/"
audience = "https://api.tero.com"
client_id = "placeholder"
webhook_key = "placeholder"

[[integrations]]
subject = "NmMLjTtX0XrnWjbe1JbRAgwEmn5lP3Sg"
name = "session"
